[pytest]
minversion = 8.0
addopts =
    -ra
    --strict-markers
    --html=reports/report.html
    --self-contained-html
    --reruns=1
    --reruns-delay=1
markers =
    authentication: tests de non-régression de l'authentification
    cart: tests E2E du panier
log_cli = true
log_cli_level = INFO
testpaths = tests
python_files = test_*.py
